import {useEffect,useMemo,useState} from 'react'
import {Link,useLocation,useNavigate,useParams} from 'react-router-dom'
import {getAttackOrigin,getAttackOriginTrace,getAttackPath,getBlastRadius,getCase,getCollectedEvidence,getEvents,getEvidence,getRemediations,getRootCause,isMockMode,updateCaseNotes} from '../api/client'
import type {AttackOriginAssessment,AttackOriginTrace,AttackPath,BlastRadius,CaseSummary,EventRecord,EvidenceRecord,IntakeEvidence,Remediation,RootCause} from '../types'
import {useAuth} from '../auth/AuthContext'
import {Icon} from '../components/Icons'
import EventTable from '../components/EventTable'
import AttackPathGraph from '../components/AttackPathGraph'
import RootCauseCard from '../components/RootCauseCard'
import BlastRadiusCard from '../components/BlastRadiusCard'
import RemediationPanel from '../components/RemediationPanel'
import AttackOriginPanel from '../components/AttackOriginPanel'
import CollectedEvidencePanel from '../components/CollectedEvidencePanel'
import EvidenceRelationshipMap from '../components/EvidenceRelationshipMap'

type Tab='Evidence'|'Events'|'Attack Path'|'Root Cause'|'Attack Origin'|'Blast Radius'|'Remediation'
const tabs:{label:Tab;icon:string;key:string}[]=[{label:'Evidence',icon:'shield',key:'evidence'},{label:'Events',icon:'pulse',key:'events'},{label:'Attack Path',icon:'nodes',key:'path'},{label:'Root Cause',icon:'search',key:'cause'},{label:'Attack Origin',icon:'search',key:'origin'},{label:'Blast Radius',icon:'layers',key:'radius'},{label:'Remediation',icon:'wrench',key:'remediation'}]

export default function CasePage(){
  const{id='CASE-2847'}=useParams(),location=useLocation(),navigate=useNavigate(),queryTab=new URLSearchParams(location.search).get('tab'),{can}=useAuth()
  const[activeTab,setActiveTab]=useState<Tab>(tabs.find(tab=>tab.key===queryTab)?.label??'Events')
  const[caseSummary,setCaseSummary]=useState<CaseSummary|null>(null),[caseLoading,setCaseLoading]=useState(true),[caseError,setCaseError]=useState(''),[events,setEvents]=useState<EventRecord[]>([]),[dataLoading,setDataLoading]=useState(true),[dataError,setDataError]=useState(''),[path,setPath]=useState<AttackPath|null>(null),[cause,setCause]=useState<RootCause|null>(null),[radius,setRadius]=useState<BlastRadius|null>(null),[remediations,setRemediations]=useState<Remediation[]>([])
  const[origin,setOrigin]=useState<AttackOriginAssessment|null>(null),[evidence,setEvidence]=useState<EvidenceRecord[]>([]),[intakeEvidence,setIntakeEvidence]=useState<(IntakeEvidence&{id:string;event_id:string})[]>([]),[trace,setTrace]=useState<AttackOriginTrace|null>(null),[originLoading,setOriginLoading]=useState(true),[traceLoading,setTraceLoading]=useState(false),[originError,setOriginError]=useState('')
  const[activityOpen,setActivityOpen]=useState(false),[eventRange,setEventRange]=useState('24h'),[eventPage,setEventPage]=useState(1)
  const[caseNotes,setCaseNotes]=useState(''),[notesBusy,setNotesBusy]=useState(false),[notesMessage,setNotesMessage]=useState('')

  useEffect(()=>{setActiveTab(tabs.find(tab=>tab.key===queryTab)?.label??'Events')},[queryTab])
  useEffect(()=>{let active=true;setCaseLoading(true);setDataLoading(true);setCaseError('');setDataError('');void (async()=>{try{const value=await getCase(id);if(!active)return;setCaseSummary(value);setCaseNotes(value.case_information?.investigator_notes??'');if(value.status==='Draft'){setEvents([]);setPath(null);setCause(null);setRadius(null);setRemediations([]);setDataLoading(false);return}const results=await Promise.allSettled([getEvents(id),getAttackPath(id),getRootCause(id),getBlastRadius(id),getRemediations(id)]);if(!active)return;const failures:string[]=[];const[e,p,c,b,r]=results;if(e.status==='fulfilled')setEvents(e.value);else failures.push('events');if(p.status==='fulfilled')setPath(p.value);else failures.push('attack path');if(c.status==='fulfilled')setCause(c.value);else failures.push('root cause');if(b.status==='fulfilled')setRadius(b.value);else failures.push('blast radius');if(r.status==='fulfilled')setRemediations(r.value);else failures.push('remediation plan');setDataError(failures.length?`Could not load ${failures.join(', ')} from the backend.`:'')}catch{if(active)setCaseError('The selected investigation could not be loaded. Check that it exists and that the backend is available.')}finally{if(active){setCaseLoading(false);setDataLoading(false)}}})();return()=>{active=false}},[id,location.key])
  useEffect(()=>{let active=true;setOrigin(null);setEvidence([]);setTrace(null);setOriginError('');if(caseSummary?.status==='Draft'){setOriginLoading(false);return()=>{active=false}}setOriginLoading(true);void Promise.allSettled([getAttackOrigin(id),getEvidence(id)]).then(([assessmentResult,evidenceResult])=>{if(!active)return;if(assessmentResult.status==='fulfilled')setOrigin(assessmentResult.value);if(evidenceResult.status==='fulfilled')setEvidence(evidenceResult.value);if(assessmentResult.status==='rejected'||evidenceResult.status==='rejected')setOriginError('Some attack-origin data could not be loaded from the connected service.')}).finally(()=>{if(active)setOriginLoading(false)});return()=>{active=false}},[id,caseSummary?.status,location.key])
  useEffect(()=>{let active=true;void getCollectedEvidence(id).then(value=>{if(active)setIntakeEvidence(value)}).catch(()=>{if(active)setIntakeEvidence([])});return()=>{active=false}},[id])

  async function traceBack(){if(!origin?.suspect)return;setTraceLoading(true);setOriginError('');try{setTrace(await getAttackOriginTrace(id,origin.suspect.id))}catch{setOriginError('The backward investigation could not be loaded from the connected service.')}finally{setTraceLoading(false)}}
  async function saveNotes(){setNotesBusy(true);setNotesMessage('');try{await updateCaseNotes(id,caseNotes);setNotesMessage('Investigator note saved.')}catch{setNotesMessage('The note could not be saved to the backend.')}finally{setNotesBusy(false)}}
  function exportCase(){const payload={case_id:id,exported_at:new Date().toISOString(),events,attack_path:path,root_cause:cause,blast_radius:radius,remediations};const url=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}));const anchor=document.createElement('a');anchor.href=url;anchor.download=`${id}-investigation.json`;anchor.click();URL.revokeObjectURL(url)}

  const attackEventIds=useMemo(()=>new Set(path?.steps.flatMap(step=>step.event_ids)??[]),[path]),currentTab=tabs.find(tab=>tab.label===activeTab)!,canApplyRemediation=can('remediation:apply')
  const latestEvent=events.reduce((latest,event)=>Math.max(latest,Date.parse(event.time)||0),0),rangeMs=eventRange==='24h'?86400000:eventRange==='7d'?7*86400000:eventRange==='30d'?30*86400000:Infinity
  const filteredEvents=useMemo(()=>rangeMs===Infinity?events:events.filter(event=>latestEvent-(Date.parse(event.time)||0)<=rangeMs),[events,latestEvent,rangeMs])
  const pageSize=5,pageCount=Math.max(1,Math.ceil(filteredEvents.length/pageSize)),pageEvents=filteredEvents.slice((eventPage-1)*pageSize,eventPage*pageSize)
  useEffect(()=>{setEventPage(1)},[eventRange,id])

  return <div className="case-page">
    <div className="case-back"><Link to="/cases">← &nbsp;All investigations</Link><span>/</span><span>{id}</span></div>
    <div className="case-header"><div className="case-title-group"><div className="case-title-line"><span className="critical-marker"/><h1>{caseSummary?.title??'Investigation'}</h1>{caseSummary&&<span className={`severity severity-${caseSummary.severity}`}><i/>{caseSummary.severity}</span>}</div><div className="case-subline"><span className="case-id">{id}</span><span className="case-sub-divider"/><span className="case-identity"><span className="identity-avatar">{caseSummary?.identity.slice(0,1).toUpperCase()??'?'}</span>{caseSummary?.identity??'Identity unavailable'}</span><span className="case-sub-divider"/><span><i className="case-live-dot"/> {caseLoading?'Loading case…':caseSummary?.status??'Status unavailable'}</span></div></div><div className="case-actions"><button type="button" className="quiet-button" onClick={exportCase} disabled={dataLoading}><Icon name="download" width={15} height={15}/> Export</button><button type="button" className="quiet-button" onClick={()=>setActivityOpen(true)}><Icon name="clock" width={15} height={15}/> Activity</button>{can('case:contain')&&<button type="button" className="case-primary" onClick={()=>navigate(`/cases/${id}?tab=remediation`)}><span className="contain-dot"/> Containment plan</button>}</div></div>
    {caseError&&<div className="inline-error" role="alert">{caseError}</div>}{dataError&&<div className="inline-error" role="alert">{dataError}</div>}
    <div className="case-metadata"><div><span>DETECTED</span><strong>{caseLoading?'Loading…':caseSummary?.detected??'Unknown'}</strong></div><div><span>DETECTION SOURCE</span><strong>{caseSummary?.source??'Unknown'}</strong></div><div><span>DATASET</span><strong>{caseSummary?.dataset_id??'Not reported'}</strong></div><div><span>ATTACK SEQUENCE</span><strong><b>{path?.steps.length??'—'}</b> observed steps</strong></div></div>
    <div className="tabbar">{tabs.map(tab=><button key={tab.key} onClick={()=>setActiveTab(tab.label)} className={activeTab===tab.label?'active':''}><Icon name={tab.icon} width={16} height={16}/>{tab.label}{tab.label==='Events'&&<span className="tab-count">{events.length}</span>}{activeTab===tab.label&&<i className="tab-underline"/>}</button>)}</div>
    <div className="case-content"><div className="content-heading"><div><div className="panel-eyebrow">CASE EVIDENCE / {currentTab.key.toUpperCase()}</div><h2>{activeTab==='Evidence'?'Collected evidence':activeTab==='Events'?'Event timeline':activeTab==='Attack Path'?'Attack sequence':activeTab==='Root Cause'?'Root cause analysis':activeTab==='Attack Origin'?'Attack origin evidence':activeTab==='Blast Radius'?'Exposure assessment':'Response and verification'}</h2><p>{activeTab==='Evidence'?'Original investigator submissions and case notes.':activeTab==='Events'?'Event records returned for this investigation.':activeTab==='Attack Path'?`${path?.steps.length??0} observed steps returned by the engine.`:activeTab==='Root Cause'?'Root cause and contributing factors derived from correlated evidence.':activeTab==='Attack Origin'?'Trace suspicious activity backward through correlated device, session, and token evidence.':activeTab==='Blast Radius'?'Resources reachable in the analyzed environment graph.':'Apply targeted actions and replay the attack sequence to verify containment.'}</p></div><div className="content-controls"><span className="telemetry-state"><i/> {isMockMode||caseSummary?.synthetic?'CONTROLLED TEST DATA':'CASE DATA'}</span>{activeTab==='Events'&&<select className="quiet-button compact range-select" aria-label="Event time range" value={eventRange} onChange={event=>setEventRange(event.target.value)}><option value="24h">Last 24 hours</option><option value="7d">Last 7 days</option><option value="30d">Last 30 days</option><option value="all">All time</option></select>}</div></div>
      {activeTab==='Evidence'&&<><section className="case-note-card"><div className="panel-eyebrow">CASE INFORMATION</div><div className="intake-detail-grid">{([['Case name',caseSummary?.case_information?.case_name],['Organization',caseSummary?.case_information?.organization],['Incident time',caseSummary?.case_information?.incident_at],['Investigator',caseSummary?.case_information?.investigator_name],['Description',caseSummary?.case_information?.description]] as const).map(([label,value])=><div key={label}><b>{label}</b><span>{value||'Not provided'}</span></div>)}</div></section>{intakeEvidence.length>0&&<EvidenceRelationshipMap evidence={intakeEvidence}/>}<CollectedEvidencePanel caseId={id} isDraft={caseSummary?.status==='Draft'} onAnalyzed={()=>navigate(`/cases/${id}?tab=events`,{replace:true})}/><section className="case-note-card"><div><div className="panel-eyebrow">INVESTIGATOR NOTE · CASE LEVEL</div><h3>Your observations</h3><p>Stored separately from TraceX Analysis.</p></div><textarea rows={4} value={caseNotes} onChange={event=>setCaseNotes(event.target.value)} placeholder="Investigator observations…"/><div className="case-note-footer"><span role="status">{notesMessage}</span><button type="button" className="case-primary" disabled={notesBusy} onClick={()=>void saveNotes()}>{notesBusy?'Saving…':'Save note'}</button></div></section></>}
      {activeTab==='Events'&&(caseSummary?.status==='Draft'?<div className="intake-empty">Evidence is saved. Review it in the Evidence tab, then choose Analyze evidence to generate events and findings.</div>:<><div className="event-insight"><div className="insight-icon">⌁</div><div><strong>{attackEventIds.size} events linked to the attack path</strong><span>Highlighted events contributed to the observed sequence.</span></div></div>{dataLoading?<div className="empty-state" role="status">Loading events for {id}…</div>:<EventTable events={pageEvents} attackEventIds={attackEventIds}/>}<div className="table-footer"><span>Showing <b>{filteredEvents.length?((eventPage-1)*pageSize+1):0}–{Math.min(eventPage*pageSize,filteredEvents.length)}</b> of <b>{filteredEvents.length}</b> correlated events</span><div className="pagination"><button type="button" disabled={dataLoading||eventPage===1} onClick={()=>setEventPage(value=>Math.max(1,value-1))} aria-label="Previous page">←</button>{Array.from({length:pageCount},(_,index)=><button type="button" key={index+1} className={eventPage===index+1?'page-current':''} onClick={()=>setEventPage(index+1)} aria-current={eventPage===index+1?'page':undefined} disabled={dataLoading}>{index+1}</button>)}<button type="button" disabled={dataLoading||eventPage===pageCount} onClick={()=>setEventPage(value=>Math.min(pageCount,value+1))} aria-label="Next page">→</button></div></div></>)}
      {activeTab==='Attack Path'&&(caseSummary?.status==='Draft'?<div className="intake-empty">Analyze the saved evidence to generate an attack sequence.</div>:path&&(path.steps.length?<AttackPathGraph path={path} evidence={intakeEvidence}/>:<div className="intake-empty">No correlated attack sequence was established from the submitted evidence. Review the evidence timeline or add more observations.</div>))}{activeTab==='Root Cause'&&(caseSummary?.status==='Draft'?<div className="intake-empty">Analyze the saved evidence to generate a root cause assessment.</div>:cause&&<RootCauseCard cause={cause}/>)}{activeTab==='Blast Radius'&&(caseSummary?.status==='Draft'?<div className="intake-empty">Analyze the saved evidence to calculate the observed blast radius.</div>:radius&&<BlastRadiusCard radius={radius}/>)}{activeTab==='Remediation'&&(caseSummary?.status==='Draft'?<div className="intake-empty">Analyze the saved evidence to request engine recommendations.</div>:<RemediationPanel caseId={id} initial={remediations} canApply={canApplyRemediation}/>)}{activeTab==='Attack Origin'&&(caseSummary?.status==='Draft'?<div className="intake-empty">Analyze the saved evidence before tracing candidate origins.</div>:<AttackOriginPanel assessment={origin} evidence={evidence} trace={trace} isSynthetic={isMockMode} loading={originLoading} traceLoading={traceLoading} error={originError} onTraceBack={()=>void traceBack}/>)}
    </div>
    {activityOpen&&<div className="modal-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget)setActivityOpen(false)}}><section className="activity-modal" role="dialog" aria-modal="true" aria-labelledby="activity-title"><div className="modal-heading"><div><div className="panel-eyebrow">CASE EVENT HISTORY</div><h2 id="activity-title">Activity · {id}</h2></div><button type="button" className="icon-button" onClick={()=>setActivityOpen(false)} aria-label="Close activity">×</button></div>{events.length?events.slice().sort((a,b)=>Date.parse(a.time)-Date.parse(b.time)).map(event=><div className="activity-entry" key={event.event_id}><i/><div><strong>{event.event_type}</strong><span>{event.identity} · {event.application} · {event.resource}</span></div><time>{event.time}</time></div>):<p className="popover-empty">{dataLoading?'Loading case events…':'No case events were returned by the backend.'}</p>}</section></div>}
  </div>
}
