import {useEffect,useMemo,useState} from 'react'
import {Link,useLocation,useParams} from 'react-router-dom'
import {getAttackOrigin,getAttackOriginTrace,getAttackPath,getBlastRadius,getEvents,getEvidence,getRemediations,getRootCause,isMockMode} from '../api/client'
import type {AttackOriginAssessment,AttackOriginTrace,AttackPath,BlastRadius,EventRecord,EvidenceRecord,Remediation,RootCause} from '../types'
import {useAuth} from '../auth/AuthContext'
import {Icon} from '../components/Icons'
import EventTable from '../components/EventTable'
import AttackPathGraph from '../components/AttackPathGraph'
import RootCauseCard from '../components/RootCauseCard'
import BlastRadiusCard from '../components/BlastRadiusCard'
import RemediationPanel from '../components/RemediationPanel'
import AttackOriginPanel from '../components/AttackOriginPanel'

type Tab='Events'|'Attack Path'|'Root Cause'|'Attack Origin'|'Blast Radius'|'Remediation'
const tabs:{label:Tab;icon:string;key:string}[]=[{label:'Events',icon:'pulse',key:'events'},{label:'Attack Path',icon:'nodes',key:'path'},{label:'Root Cause',icon:'search',key:'cause'},{label:'Attack Origin',icon:'search',key:'origin'},{label:'Blast Radius',icon:'layers',key:'radius'},{label:'Remediation',icon:'wrench',key:'remediation'}]

export default function CasePage(){
  const{id='CASE-2847'}=useParams(),location=useLocation(),queryTab=new URLSearchParams(location.search).get('tab'),{can}=useAuth()
  const[activeTab,setActiveTab]=useState<Tab>(tabs.find(tab=>tab.key===queryTab)?.label??'Events')
  const[events,setEvents]=useState<EventRecord[]>([]),[path,setPath]=useState<AttackPath|null>(null),[cause,setCause]=useState<RootCause|null>(null),[radius,setRadius]=useState<BlastRadius|null>(null),[remediations,setRemediations]=useState<Remediation[]>([])
  const[origin,setOrigin]=useState<AttackOriginAssessment|null>(null),[evidence,setEvidence]=useState<EvidenceRecord[]>([]),[trace,setTrace]=useState<AttackOriginTrace|null>(null),[originLoading,setOriginLoading]=useState(true),[traceLoading,setTraceLoading]=useState(false),[originError,setOriginError]=useState('')

  useEffect(()=>{setActiveTab(tabs.find(tab=>tab.key===queryTab)?.label??'Events')},[queryTab])
  useEffect(()=>{let active=true;void Promise.all([getEvents(),getAttackPath(),getRootCause(),getBlastRadius(),getRemediations()]).then(([e,p,c,b,r])=>{if(active){setEvents(e);setPath(p);setCause(c);setRadius(b);setRemediations(r)}}).catch(()=>undefined);return()=>{active=false}},[id])
  useEffect(()=>{let active=true;setOrigin(null);setEvidence([]);setTrace(null);setOriginError('');setOriginLoading(true);void Promise.allSettled([getAttackOrigin(id),getEvidence(id)]).then(([assessmentResult,evidenceResult])=>{if(!active)return;if(assessmentResult.status==='fulfilled')setOrigin(assessmentResult.value);if(evidenceResult.status==='fulfilled')setEvidence(evidenceResult.value);if(assessmentResult.status==='rejected'||evidenceResult.status==='rejected')setOriginError('Some attack-origin data could not be loaded from the connected service.')}).finally(()=>{if(active)setOriginLoading(false)});return()=>{active=false}},[id])

  async function traceBack(){if(!origin?.suspect)return;setTraceLoading(true);setOriginError('');try{setTrace(await getAttackOriginTrace(id,origin.suspect.id))}catch{setOriginError('The backward investigation could not be loaded from the connected service.')}finally{setTraceLoading(false)}}
  const attackEventIds=useMemo(()=>new Set(path?.steps.flatMap(step=>step.event_ids)??[]),[path]),currentTab=tabs.find(tab=>tab.label===activeTab)!,canApplyRemediation=can('remediation:apply')

  return <div className="case-page"><div className="case-back"><Link to="/cases">← &nbsp;All investigations</Link><span>/</span><span>{id}</span></div><div className="case-header"><div className="case-title-group"><div className="case-title-line"><span className="critical-marker"/><h1>Compromised service identity</h1><span className="severity severity-critical"><i/>CRITICAL</span></div><div className="case-subline"><span className="case-id">{id}</span><span className="case-sub-divider"/><span className="case-identity"><span className="identity-avatar">S</span>svc-orders-prod</span><span className="case-sub-divider"/><span><i className="case-live-dot"/> Investigating</span></div></div><div className="case-actions"><button className="quiet-button"><Icon name="download" width={15} height={15}/> Export</button><button className="quiet-button"><Icon name="clock" width={15} height={15}/> Activity</button>{can('case:contain')&&<button className="case-primary"><span className="contain-dot"/> Contain threat</button>}</div></div><div className="case-metadata"><div><span>DETECTED</span><strong>Oct 06, 2025 <i>·</i> 09:42:18 UTC</strong></div><div><span>DETECTION RULE</span><strong>Identity anomaly <i>·</i> High confidence</strong></div><div><span>INITIAL ACCESS</span><strong>Token replay <i>·</i> Unfamiliar device</strong></div><div><span>ATTACK SEQUENCE</span><strong><b>07</b> observed steps</strong></div></div><div className="tabbar">{tabs.map(tab=><button key={tab.key} onClick={()=>setActiveTab(tab.label)} className={activeTab===tab.label?'active':''}><Icon name={tab.icon} width={16} height={16}/>{tab.label}{tab.label==='Events'&&<span className="tab-count">{events.length}</span>}{activeTab===tab.label&&<i className="tab-underline"/>}</button>)}</div><div className="case-content"><div className="content-heading"><div><div className="panel-eyebrow">CASE EVIDENCE / {currentTab.key.toUpperCase()}</div><h2>{activeTab==='Events'?'Event timeline':activeTab==='Attack Path'?'Attack sequence':activeTab==='Root Cause'?'Root cause analysis':activeTab==='Attack Origin'?'Attack origin evidence':activeTab==='Blast Radius'?'Exposure assessment':'Response and verification'}</h2><p>{activeTab==='Events'?'Raw identity telemetry correlated to this investigation.':activeTab==='Attack Path'?'Seven connected actions traced across identities, apps, and resources.':activeTab==='Root Cause'?'The conditions that enabled the initial compromise.':activeTab==='Attack Origin'?'Trace suspicious activity backward through correlated device, session, and token evidence.':activeTab==='Blast Radius'?'A map of downstream access available to the compromised credential.':'Apply targeted actions and replay the attack sequence to verify containment.'}</p></div><div className="content-controls"><span className="telemetry-state"><i/> LIVE TELEMETRY</span><button className="quiet-button compact">Last 24 hours&nbsp;⌄</button></div></div>
    {activeTab==='Events'&&<><div className="event-insight"><div className="insight-icon">⌁</div><div><strong>{attackEventIds.size} events linked to the attack path</strong><span>Highlighted events contributed to the observed sequence.</span></div><div className="insight-severity"><i/> 1 critical&nbsp; <i/> 3 high</div></div><EventTable events={events} attackEventIds={attackEventIds}/><div className="table-footer"><span>Showing <b>{events.length}</b> correlated events</span><div className="pagination"><button disabled>←</button><button className="page-current">1</button><button>2</button><button>3</button><span>…</span><button>8</button><button>→</button></div></div></>}
    {activeTab==='Attack Path'&&path&&<AttackPathGraph path={path}/>}{activeTab==='Root Cause'&&cause&&<RootCauseCard cause={cause}/>}{activeTab==='Blast Radius'&&radius&&<BlastRadiusCard radius={radius}/>}{activeTab==='Remediation'&&remediations.length>0&&<RemediationPanel initial={remediations} canApply={canApplyRemediation}/>}{activeTab==='Attack Origin'&&<AttackOriginPanel assessment={origin} evidence={evidence} trace={trace} isSynthetic={isMockMode} loading={originLoading} traceLoading={traceLoading} error={originError} onTraceBack={()=>void traceBack()}/>}
  </div></div>
}
