import {useMemo,useState} from 'react'
import ReactFlow,{Background,Controls,type Edge,type Node,Position} from 'reactflow'
import type {AttackPath,AttackStep,IntakeEvidence} from '../types'
const tones=['cyan','blue','violet','amber','rose']
type SavedEvidence=IntakeEvidence&{id:string;event_id:string}

export default function AttackPathGraph({path,evidence=[]}:{path:AttackPath;evidence?:SavedEvidence[]}){
  const[selected,setSelected]=useState<AttackStep|null>(null)
  const{nodes,edges}=useMemo(()=>{const nodes:Node[]=[],edges:Edge[]=[];path.steps.forEach((step,index)=>{const tone=tones[Math.min(index,tones.length-1)];nodes.push({id:`step-${step.step}`,type:'default',position:{x:index*235,y:70+(index%2?94:0)},sourcePosition:Position.Right,targetPosition:Position.Left,data:{label:<button className={`graph-node graph-${tone}`} onClick={()=>setSelected(step)}><span className="graph-node-top"><span className="node-index">{String(step.step).padStart(2,'0')}</span><span className="node-dot"/></span><strong>{step.target}</strong><span className="node-stage">{step.stage}</span><span className="node-edge">{step.permission}</span></button>}});if(index>0)edges.push({id:`edge-${index}`,source:`step-${path.steps[index-1].step}`,target:`step-${step.step}`,animated:true,style:{stroke:'#526178',strokeWidth:1.4},label:step.permission,labelStyle:{fill:'#98a4b7',fontSize:9,fontFamily:'DM Mono'},labelBgStyle:{fill:'#111925',fillOpacity:.92}})});return{nodes,edges}},[path])
  const selectedEvidence=selected?evidence.filter(item=>selected.event_ids.includes(item.event_id)):[]
  return <div className="graph-layout"><div className="graph-canvas"><div className="graph-kicker"><span className="live-line"/> OBSERVED ATTACK SEQUENCE <span className="graph-count">{path.steps.length} STEPS</span></div><div className="react-flow-host"><ReactFlow nodes={nodes} edges={edges} fitView fitViewOptions={{padding:.17}} minZoom={.35} maxZoom={1.35} proOptions={{hideAttribution:true}} nodesDraggable={false} nodesConnectable={false} onNodeClick={(_,node)=>setSelected(path.steps.find(step=>`step-${step.step}`===node.id)??null)}><Background color="#202b3b" gap={24} size={1}/><Controls showInteractive={false}/></ReactFlow></div><div className="graph-legend"><span><i className="legend-cyan"/> Identity</span><span><i className="legend-violet"/> Application</span><span><i className="legend-amber"/> Privilege escalation</span><span><i className="legend-rose"/> Sensitive resource</span></div></div><aside className="step-panel">{selected?<><div className="panel-eyebrow">ATTACK STEP {String(selected.step).padStart(2,'0')}</div><h3>{selected.summary}</h3><p className="step-route">{selected.source}<span>→</span>{selected.target}</p><div className="detail-separator"/><div className="detail-row"><span>Technique</span><strong>{selected.stage}</strong></div><div className="detail-row"><span>Permission</span><code>{selected.permission}</code></div><div className="detail-row"><span>Observed at</span><strong>{new Date(selected.timestamp).toLocaleString()}</strong></div><div className="detail-row"><span>Evidence IDs</span><div className="event-chips">{selected.event_ids.map(id=><code key={id}>{id}</code>)}</div></div>{selectedEvidence.length>0&&selectedEvidence.map(item=><section className="graph-evidence-detail" key={item.id}><div className="panel-eyebrow">SUBMITTED EVIDENCE</div>{([['Identity',item.identity],['Device',item.device_id],['Source IP',item.source_ip],['Destination IP',item.destination_ip],['Session',item.session_id],['Token',item.token_id],['API / service',item.api_service],['User-agent',item.user_agent],['Process',item.process],['Authentication',item.authentication],['Network connection',item.network_connection],['Investigator note',item.investigator_notes]] as const).filter(([,value])=>value).map(([label,value])=><div className="detail-row" key={label}><span>{label}</span><strong>{value}</strong></div>)}</section>)}<div className="detail-row"><span>Step confidence</span><strong>Not scored by the current engine</strong></div><div className="evidence-note"><span className="evidence-pulse"/> Graph step references evidence returned by the engine</div></>:<div className="step-empty"><div className="step-empty-icon">⌁</div><strong>Select a node to inspect</strong><span>Explore the sequence to see supporting evidence and access transitions.</span></div>}</aside></div>
}
