import {useEffect,useMemo,useState} from 'react'
import {analyzeCase,getCollectedEvidence} from '../api/client'
import type {IntakeEvidence} from '../types'

type SavedEvidence=IntakeEvidence&{id:string;event_id:string}
const labels:Record<keyof IntakeEvidence,string>={evidence_type:'Evidence type',timestamp:'Timestamp',source:'Source',source_ip:'Source IP',destination_ip:'Destination IP',device_id:'Device ID',identity:'User / identity',session_id:'Session ID',token_id:'Token ID',user_agent:'User-agent',process:'Process / execution',authentication:'Authentication',network_connection:'Network connection',api_service:'API / service',description:'Description',investigator_notes:'Investigator note'}
export default function CollectedEvidencePanel({caseId,isDraft,onAnalyzed}:{caseId:string;isDraft:boolean;onAnalyzed:()=>void}){
  const[items,setItems]=useState<SavedEvidence[]>([]),[error,setError]=useState(''),[query,setQuery]=useState(''),[selected,setSelected]=useState<SavedEvidence|null>(null),[busy,setBusy]=useState(false),[analysisMessage,setAnalysisMessage]=useState('')
  useEffect(()=>{let active=true;void getCollectedEvidence(caseId).then(value=>{if(active){setItems(value);setError('')}}).catch(()=>{if(active)setError('The submitted evidence records could not be loaded from the backend.')});return()=>{active=false}},[caseId])
  const visible=useMemo(()=>items.filter(item=>Object.values(item).join(' ').toLowerCase().includes(query.trim().toLowerCase())).sort((a,b)=>Date.parse(a.timestamp)-Date.parse(b.timestamp)),[items,query])
  async function runAnalysis(){setBusy(true);setAnalysisMessage('');try{await analyzeCase(caseId);setAnalysisMessage('Evidence analyzed by TraceX.');onAnalyzed()}catch{setAnalysisMessage('Analysis could not be completed by the backend. Review the evidence and retry.')}finally{setBusy(false)}}
  if(error)return <div className="inline-error" role="alert">{error}</div>
  return <section className="collected-evidence"><div className="intake-section-title"><div><div className="panel-eyebrow">ORIGINAL SUBMITTED RECORDS</div><h2>Collected evidence</h2><p>Evidence as entered by the investigator, separate from TraceX Analysis.</p></div><span>{items.length} RECORDS</span></div>{analysisMessage&&<div className="session-message" role="status">{analysisMessage}</div>}<div className="evidence-list-heading"><h3>Evidence timeline</h3><div><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search evidence" aria-label="Search collected evidence"/><span>Sorted oldest first</span></div></div>{visible.length===0?<div className="intake-empty">No evidence records were submitted for this case.</div>:<div className="table-wrap"><table className="intake-evidence-table"><thead><tr><th>TIMESTAMP</th><th>TYPE</th><th>IDENTITY</th><th>DEVICE</th><th>SOURCE</th><th>DESCRIPTION</th><th/></tr></thead><tbody>{visible.map(item=><tr key={item.id}><td>{new Date(item.timestamp).toLocaleString()}</td><td>{item.evidence_type}</td><td>{item.identity||'Unknown'}</td><td>{item.device_id||'Unknown'}</td><td>{item.source_ip||item.source||'Unknown'}</td><td>{item.description||'No description'}</td><td><button className="intake-row-action" type="button" onClick={()=>setSelected(item)}>Details</button></td></tr>)}</tbody></table></div>}{isDraft&&items.length>0&&<div className="intake-footer"><span>Run analysis only after reviewing the saved evidence.</span><button type="button" className="case-primary" disabled={busy} onClick={()=>void runAnalysis()}>{busy?'Analyzing…':'Analyze evidence'}</button></div>}{selected&&<div className="modal-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget)setSelected(null)}}><section className="activity-modal" role="dialog" aria-modal="true" aria-labelledby="evidence-detail-title"><div className="modal-heading"><div><div className="panel-eyebrow">INVESTIGATOR SUBMISSION</div><h2 id="evidence-detail-title">{selected.evidence_type}</h2></div><button type="button" className="icon-button" onClick={()=>setSelected(null)} aria-label="Close evidence details">×</button></div><div className="intake-detail-grid">{Object.entries(labels).map(([key,label])=>{const value=selected[key as keyof IntakeEvidence];return value?<div key={key}><b>{label}</b><span>{key==='timestamp'?new Date(String(value)).toLocaleString():String(value)}</span></div>:null})}</div><div className="detail-row"><span>Evidence record ID</span><code>{selected.id}</code></div><div className="detail-row"><span>TraceX event ID</span><code>{selected.event_id}</code></div></section></div>}</section>
}
