import {useMemo,useState} from 'react'
import ReactFlow,{Background,Controls,type Edge,type Node,Position} from 'reactflow'
import type {IntakeEvidence} from '../types'
type SavedEvidence=IntakeEvidence&{id:string;event_id:string}
const entityFields:{key:keyof IntakeEvidence;label:string;kind:string}[]=[{key:'source_ip',label:'Source IP',kind:'ip'},{key:'device_id',label:'Device',kind:'device'},{key:'identity',label:'Identity',kind:'identity'},{key:'session_id',label:'Session',kind:'session'},{key:'token_id',label:'Token',kind:'token'},{key:'api_service',label:'API / service',kind:'service'},{key:'destination_ip',label:'Destination IP',kind:'ip'}]
export default function EvidenceRelationshipMap({evidence}:{evidence:SavedEvidence[]}){
  const[selected,setSelected]=useState<{id:string;label:string;kind:string}|null>(null)
  const{nodes,edges,records}=useMemo(()=>{const nodeMap=new Map<string,{id:string;label:string;kind:string}>(),edges:Edge[]=[],linked=new Map<string,SavedEvidence[]>();for(const item of evidence){const present=entityFields.flatMap(field=>{const value=item[field.key];if(!value)return[];const id=`${field.kind}:${String(value)}`;nodeMap.set(id,{id,label:String(value),kind:field.kind});linked.set(id,[...(linked.get(id)??[]),item]);return[{id,kind:field.kind}]});for(let index=1;index<present.length;index++){const source=present[index-1].id,target=present[index].id;edges.push({id:`${item.id}:${index}`,source,target,label:'same evidence record',style:{stroke:'#4d6374',strokeWidth:1},labelStyle:{fill:'#91a0b1',fontSize:8},labelBgStyle:{fill:'#111925',fillOpacity:.95}})}}const nodes:Node[]=[...nodeMap.values()].map((node,index)=>({id:node.id,position:{x:index*210,y:index%2?110:35},sourcePosition:Position.Right,targetPosition:Position.Left,data:{label:<button type="button" className={`evidence-map-node node-${node.kind}`} onClick={()=>setSelected(node)}><span>{node.kind}</span><strong>{node.label}</strong></button>}}));return{nodes,edges,records:linked}},[evidence])
  const related=selected?records.get(selected.id)??[]:[]
  return <div className="graph-layout evidence-map-layout"><div className="graph-canvas"><div className="graph-kicker"><span className="live-line"/> EVIDENCE RELATIONSHIP MAP <span className="graph-count">{nodes.length} ENTITIES</span></div>{nodes.length?<div className="react-flow-host"><ReactFlow nodes={nodes} edges={edges} fitView fitViewOptions={{padding:.2}} minZoom={.3} maxZoom={1.4} proOptions={{hideAttribution:true}} nodesDraggable={false} nodesConnectable={false} onNodeClick={(_,node)=>{const[kind,...value]=node.id.split(':');setSelected({id:node.id,label:value.join(':'),kind})}}><Background color="#202b3b" gap={24} size={1}/><Controls showInteractive={false}/></ReactFlow></div>:<div className="intake-empty">No entity relationships can be drawn from the submitted fields yet.</div>}<div className="graph-legend"><span>Lines mean entities were co-reported in one evidence item; they do not assert causality.</span></div></div><aside className="step-panel">{selected?<><div className="panel-eyebrow">EVIDENCE ENTITY · {selected.kind.toUpperCase()}</div><h3>{selected.label}</h3><div className="detail-row"><span>Investigator assessment</span><strong>Unclassified</strong></div><div className="detail-row"><span>Confidence</span><strong>Not scored by the engine</strong></div><div className="detail-separator"/><div className="panel-eyebrow">RELATED SUBMISSIONS · {related.length}</div>{related.map(item=><article className="graph-evidence-detail" key={item.id}><strong>{item.evidence_type} · {new Date(item.timestamp).toLocaleString()}</strong><span>{item.description||'No description supplied'}</span><span>Evidence ID: {item.event_id}</span>{item.investigator_notes&&<span>INVESTIGATOR NOTE: {item.investigator_notes}</span>}</article>)}</>:<div className="step-empty"><div className="step-empty-icon">⌁</div><strong>Select an entity</strong><span>Inspect the submitted records that include this entity. No entity is automatically labelled an attacker.</span></div>}</aside></div>
}
