import {useEffect,useMemo,useState} from 'react'
import {useLocation,useNavigate} from 'react-router-dom'
import {getCases} from '../api/client'
import type {CaseSummary} from '../types'
import {useAuth} from '../auth/AuthContext'
import {Icon} from './Icons'
import NewInvestigationButton from './NewInvestigationButton'

export default function Topbar(){
  const navigate=useNavigate(),location=useLocation(),caseId=location.pathname.match(/^\/cases\/([^/]+)/)?.[1],{session,logout}=useAuth(),user=session!.user,role=user.role==='admin'?'Admin':'Analyst'
  const[searchOpen,setSearchOpen]=useState(false),[notificationsOpen,setNotificationsOpen]=useState(false),[query,setQuery]=useState(''),[cases,setCases]=useState<CaseSummary[]>([]),[searchError,setSearchError]=useState('')
  useEffect(()=>{let active=true;void getCases().then(value=>{if(active)setCases(value)}).catch(()=>{if(active)setSearchError('Investigations could not be loaded.')});return()=>{active=false}},[])
  useEffect(()=>{const onKeyDown=(event:KeyboardEvent)=>{if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='k'){event.preventDefault();setSearchOpen(true);setNotificationsOpen(false)}if(event.key==='Escape'){setSearchOpen(false);setNotificationsOpen(false)}};window.addEventListener('keydown',onKeyDown);return()=>window.removeEventListener('keydown',onKeyDown)},[])
  const results=useMemo(()=>{const needle=query.trim().toLowerCase();return needle?cases.filter(item=>[item.id,item.title,item.identity,item.source,item.status].some(value=>value.toLowerCase().includes(needle))).slice(0,6):cases.slice(0,5)},[cases,query])
  const alerts=cases.filter(item=>item.status!=='Resolved'&&(item.severity==='critical'||item.severity==='high')).slice(0,5)
  const openCase=(id:string)=>{setSearchOpen(false);setNotificationsOpen(false);setQuery('');navigate(`/cases/${id}`)}
  return <header className="topbar"><div className="breadcrumbs"><span>Workspace</span><Icon name="chevron" width={13} height={13}/><span>Investigations</span>{caseId&&<><Icon name="chevron" width={13} height={13}/><strong>{caseId}</strong></>}</div><div className="top-actions"><button type="button" className="search-trigger" onClick={()=>{setSearchOpen(true);setNotificationsOpen(false)}}><Icon name="search"/><span>Search anything...</span><kbd>⌘ K</kbd></button><span className="top-divider"/><div className="notification-wrap"><button type="button" className="icon-button notification" aria-label="Notifications" aria-expanded={notificationsOpen} onClick={()=>{setNotificationsOpen(value=>!value);setSearchOpen(false)}}><Icon name="bell"/>{alerts.length>0&&<i/>}</button>{notificationsOpen&&<div className="top-popover notification-popover"><div className="top-popover-heading"><strong>Open alerts</strong><button type="button" className="popover-close" onClick={()=>setNotificationsOpen(false)} aria-label="Close notifications">×</button></div>{alerts.length?alerts.map(item=><button type="button" className="top-result" key={item.id} onClick={()=>openCase(item.id)}><span className={`severity-dot severity-dot-${item.severity}`}/><span><strong>{item.title}</strong><small>{item.id} · {item.severity}</small></span><Icon name="chevron" width={14} height={14}/></button>):<p className="popover-empty">No open high severity alerts.</p>}</div>}</div><div className="header-identity"><div className="top-avatar">{user.email.slice(0,2).toUpperCase()}</div><div className="header-user-copy"><strong title={user.email}>{user.display_name??user.email}</strong><span>{role}</span></div></div><button type="button" className="header-logout" onClick={()=>void logout()}>Logout</button><NewInvestigationButton/>
    {searchOpen&&<div className="search-overlay" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)setSearchOpen(false)}}><section className="top-popover search-dialog" role="dialog" aria-modal="true" aria-label="Search investigations"><div className="search-dialog-input"><Icon name="search"/><input autoFocus value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search investigations…" aria-label="Search investigations"/><kbd>ESC</kbd><button type="button" className="popover-close" onClick={()=>setSearchOpen(false)} aria-label="Close search">×</button></div><div className="search-results-label">{query.trim()?'MATCHING INVESTIGATIONS':'RECENT INVESTIGATIONS'}</div>{searchError&&<p className="popover-empty">{searchError}</p>}{results.map(item=><button type="button" className="top-result" key={item.id} onClick={()=>openCase(item.id)}><span className={`severity-dot severity-dot-${item.severity}`}/><span><strong>{item.title}</strong><small>{item.id} · {item.identity} · {item.status}</small></span><Icon name="chevron" width={14} height={14}/></button>)}{!searchError&&results.length===0&&<p className="popover-empty">No investigations match “{query}”.</p>}<div className="search-dialog-foot">Searches case IDs, titles, identities, and sources</div></section></div>}
  </div></header>
}
